#!/usr/bin/env zsh

### ZSH stuff
export ZSH="${HOME}/.oh-my-zsh"
ZSH_THEME="gnzh"
plugins=(
  docker
  docker-compose
  git
  python
  ubuntu
)

source "${ZSH}/oh-my-zsh.sh"

### PATH
for p in \
  "${HOME}/.local/bin" \
  "${HOME}/.local/go/bin" \
  "${HOME}/go/bin" \
  "${HOME}/.cargo/bin" \
  "/usr/games" \
  "/usr/local/games" \
; do
  if [[ ! "${PATH}" =~ ${p} ]]; then
    export PATH="${p}:${PATH}"
  fi
done

### Aliases
alias aws-azure-login="npx aws-azure-login --no-prompt "
alias cfn='aws cloudformation '
alias dsp='docker system prune'
alias dspv='docker system prune --volumes'
alias k='kubectl '
alias tclsh='rlwrap tclsh '
alias tf='terraform '
alias va='source venv/bin/activate'
alias vc='python3 -m venv --clear venv'

### Vars
export AWS_DEFAULT_REGION='us-east-2'
[[ -f "${HOME}/.aws_var_overrides" ]] && source "${HOME}/.aws_var_overrides"

export DOCKER_BUILDKIT=1

export OSC_INFRA_ROOT="${HOME}/repos/opensourcecorp/osc-infra"
# export VAGRANT_EXPERIMENTAL="disks"
export VAGRANT_DEFAULT_PROVIDER=libvirt

# VSCode is so fucking stupid, and needs this undocumented var for actually
# opening a Remote
export WSL_DISTRO_NAME='debian'

### Completions
if command -v kubectl > /dev/null; then
  source <(kubectl completion zsh)
fi

### Functions
git-branch-cleanup() {
  git fetch --prune 2>&1 \
  | awk '{ gsub(/origin\//, "", $5) ; print $5 }' \
  | xargs -I{} git branch -D || true
}

# Quick-and-dirty but handy SQLite func for operating directly on CSVs
csvql() {
  sqlite3 \
    ':memory:' \
    -cmd '.mode csv' \
    -cmd ".import $1 data" \
    -cmd '.mode column' \
    "${2}"
}

github-super-linter() {
  local result=0

  docker run \
    --rm \
    -it \
    -e RUN_LOCAL=true \
    -e USE_FIND_ALGORITHM=true \
    -e IGNORE_GITIGNORED_FILES=true \
    -e FILTER_REGEX_EXCLUDE='.*testdata/.*|.*vendor/.*|.*\.vmdk|.*\.ovf|.*\.box|.*\.iso' \
    -e VALIDATE_NATURAL_LANGUAGE=false \
    -e VALIDATE_GO_MODULES=true \
    -v "${PWD}":/tmp/lint \
    ghcr.io/super-linter/super-linter:slim-v5 \
  || result="$?"

  return "${result}"
}

### THE FOLLOWING NEED TO RUN LAST
# Check if running under WSL, and NOT WSL Debian
if uname -a | grep -q -i -E 'microsoft|wsl' ; then # && ! grep -q 'sid' /etc/*-release ; then
  if [[ -f /usr/lib/binfmt.d/WSLInterop.conf ]]; then
    printf 'WARNING: the file at /usr/lib/binfmt.d/WSLInterop.conf is there until MS fixes systemd-enabled WSL2 interop -- delete later when no longer needed\n'
    printf 'Additional details here: https://github.com/microsoft/WSL/issues/8843#issuecomment-1255546484\n'
  fi
  sudo usermod -aG kvm,libvirt "${USER}" || true
  sudo bash -c '[[ -f /etc/resolv.conf ]] || sudo printf "nameserver 8.8.8.8\nnameserver 1.1.1.1\n" > /etc/resolv.conf'
  export VAGRANT_DEFAULT_PROVIDER='libvirt'
fi

# This needs to run DEAD LAST, since it's an exec call
{ [[ -z "${TMUX}" ]] && exec tmux ;} || true
