---
- name: "Desktop system initialization"
  hosts: "localhost"
  remote_user: "root"

  vars:
    user: "ryan"
    debian_release_number: "13"
    debian_release_alias: "trixie"
    apt_repos:
      - name: vscode
        uri: "https://packages.microsoft.com/repos/code"
        key_uri: "https://packages.microsoft.com/keys/microsoft.asc"
        suite: "stable"
        component: "main"
        packages:
          - "code"
    godot_version: "v4.1.1-stable"
    pixelorama_version: "v1.1.1"

  tasks:
    - name: "Add Debian repos"
      become: true
      ansible.builtin.deb822_repository:
        name: "{{ item.name }}"
        types: "deb"
        uris: "{{ item.uri }}"
        suites: "{{ item.suite }}"
        components: "{{ item.component }}"
        signed_by: "{{ item.key_uri }}"
        architectures: ["amd64"]
      loop: "{{ apt_repos }}"

    - name: "Install packages from new repos"
      become: true
      ansible.builtin.apt:
        pkg: "{{ item.packages }}"
        update_cache: true
        autoclean: true
        autoremove: true
        clean: true
      loop: "{{ apt_repos }}"

    # - name: "Download Godot Engine"
    #   ansible.builtin.get_url:
    #     url: "https://github.com/godotengine/godot/releases/download/{{ godot_version }}/Godot_{{ godot_version }}_linux.x86_64.zip"
    #     dest: "/tmp/godot.zip"

    # - name: "Unarchive Godot Engine"
    #   # TODO: rename this post-extract (it's just one file)
    #   ansible.builtin.unarchive:
    #     src: "/tmp/godot.zip"
    #     dest: "/home/{{ user }}/.local/bin"

    # - name: "Make Desktop entry for Godot Engine"
    #   ansible.builtin.file:
    #     dest: "/home/{{ user }}/.local/share/applications/godot.desktop"
    #     contents: |
    #       #!/usr/bin/env xdg-open
    #       [Desktop Entry]
    #       Name=Godot Engine
    #       Comment=Godot game development engine
    #       Exec=/home/ryan/.local/bin/godot
    #       Terminal=false
    #       Type=Application
    #       Categories=Development;Game;

    # - name: "Make Godot projects tree"
    #   ansible.builtin.file:
    #     path: "/home/{{ user }}/godot/projects"
    #     state: "directory"
    #     mode: "0755"
    #     owner: "{{ user }}"
    #     group: "{{ user }}"

    # - name: "Download Pixelorama"
    #   ansible.builtin.get_url:
    #     url: "https://github.com/Orama-Interactive/Pixelorama/releases/download/{{ pixelorama_version }}/Pixelorama-Linux-64bit.tar.gz"
    #     dest: "/tmp/pixelorama.zip"

    # - name: "Unarchive Pixelorama"
    #   # TODO: rename these post-extract (you need the binary, AND the .pck file)
    #   ansible.builtin.unarchive:
    #     src: "/tmp/pixelorama.zip"
    #     dest: "/home/{{ user }}/.local/bin"

    # - name: "Make Desktop entry for Pixelorama"
    #   ansible.builtin.file:
    #     dest: "/home/{{ user }}/.local/share/applications/pixelorama.desktop"
    #     contents: |
    #       #!/usr/bin/env xdg-open
    #       [Desktop Entry]
    #       Name=Pixelorama
    #       Comment=Pixelorama - make pixel art
    #       Exec=/home/ryan/.local/bin/pixelorama
    #       Terminal=false
    #       Type=Application
    #       Categories=Development;Game;
