- name: "Remove old-format sources.list"
  become: true
  ansible.builtin.file:
    path: "/etc/apt/sources.list"
    state: "absent"

- name: "Add Debian Unstable repo"
  become: true
  ansible.builtin.deb822_repository:
    name: "debian-unstable"
    types: "deb"
    uris: "http://deb.debian.org/debian"
    suites: "unstable"
    components:
      - main
      - contrib
      - non-free
      - non-free-firmware
    signed_by: "/usr/share/keyrings/debian-archive-keyring.gpg"
    architectures: ["amd64"]

- name: "Upgrade system"
  become: true
  ansible.builtin.apt:
    update_cache: true
    upgrade: "full"
    autoclean: true
    autoremove: true
