#!/usr/bin/env bash

# shellcheck disable=SC1091
source "${HOME}/.sharedrc"

shopt -s globstar

### Shell prompt
# Built with help from: https://bash-prompt-generator.org/
export GIT_PS1_SHOWDIRTYSTATE=true
export GIT_PS1_SHOWSTASHSTATE=true
export GIT_PS1_SHOWUNTRACKEDFILES=true
export GIT_PS1_STATESEPARATOR=''
PROMPT_COMMAND='PS1_CMD1=$(__git_ps1 " (%s)")'
PS1='\[\e[92m\]\u@\h \[\e[96m\]\w\[\e[93m\]${PS1_CMD1}\[\e[0m\] [\[\e[91m\]$?\[\e[0m\]]\n-> '

if [[ ! -f "${HOME}/.git-prompt.sh" ]]; then
  curl -fsSL \
    -o "${HOME}/.git-prompt.sh" \
    'https://raw.githubusercontent.com/git/git/refs/heads/master/contrib/completion/git-prompt.sh'
fi

# shellcheck disable=1091
source "${HOME}/.git-prompt.sh"

### Completions
bind 'set show-all-if-ambiguous on'
bind 'TAB:menu-complete'
bind '"\e[Z":menu-complete-backward'

### mise-en-place
eval "$(mise activate bash)"

# shellcheck disable=SC1091
source "${HOME}/.sharedrc-final"
