#!/usr/bin/env bash

####################################################################################################
# This file is intended to be sourced by each bash-compatible shell rc file (.bashrc, .zshrc, etc).
####################################################################################################

### PATH
for p in \
  "${HOME}/.local/bin" \
  "${HOME}/.local/go/bin" \
  "${HOME}/go/bin" \
  "/usr/games" \
  "/usr/local/games" \
; do
  if [[ ! "${PATH}" =~ ${p} ]]; then
    export PATH="${p}:${PATH}"
  fi
done

### Aliases
alias cfn='aws cloudformation '
alias dsp='docker system prune'
alias dspv='docker system prune --volumes'
alias k='kubectl '
alias k9s='k9s --headless --logoless '
alias s="source ${HOME}/.zshrc"
alias tclsh='rlwrap tclsh '
alias tf='terraform '
# System update
# Name chosen because this matches one of the oh-my-zsh aliases for all this
alias agud='sudo apt update && sudo apt dist-upgrade && sudo apt autoremove -y && sudo apt autoclean -y'
# Git aliases
alias gst='git status'
alias gco='git checkout '
alias gl='git pull'
alias gc='git commit '
alias gp='git push'

### Vars
export AWS_DEFAULT_REGION='us-east-2'
export DOCKER_BUILDKIT=1
export EDITOR='nano'
export GITHUB_TOKEN="$(gh auth token)"
export OSC_INFRA_ROOT="${HOME}/repos/opensourcecorp/osc-infra"

# export VAGRANT_EXPERIMENTAL="disks"
export VAGRANT_DEFAULT_PROVIDER=libvirt

# VSCode is so fucking stupid, and needs this undocumented var for actually opening a Remote
export WSL_DISTRO_NAME='debian'

### Functions
is-linux() {
  if [[ "$(uname -s)" == "Linux" ]] ; then
    return 0
  fi

  return 1
}

is-macos() {
  if [[ "$(uname -s)" == "Darwin" ]] ; then
    return 0
  fi

  return 1
}

kctx() {
  local ctx="${1:-}"
  if [[ -z "${ctx}" ]] ; then
    printf 'Current context is:\n%s\n' "$(kubectl config current-context || echo '*none*')"
    printf '\n'
    printf 'Available contexts are:\n'
    kubectl config get-contexts --output name | sort -h
  else
    kubectl config use-context "${ctx}"
  fi
}

git-branch-cleanup() {
  git fetch --prune 2>&1 \
  | awk '{ gsub(/origin\//, "", $5) ; print $5 }' \
  | xargs -I{} git branch -D {} || true
}

# Quick-and-dirty but handy SQLite func for operating directly on CSVs
csvql() {
  sqlite3 \
    ':memory:' \
    -cmd '.mode csv' \
    -cmd ".import $1 data" \
    -cmd '.mode column' \
    "${2}"
}

### Install mise if it isn't already
if ! command -v mise > /dev/null ; then
  printf 'NOTE: mise not found on PATH, will install\n' >&2

  # Defaults based on the machines I usually run
  os='linux'
  arch='x64'

  ggrep='grep'
  if [[ "$(uname -s)" == "Darwin" ]] ; then
    os='macos'
    ggrep='ggrep'
  fi
  if [[ "$(uname -m)" == "arm64" ]] ; then
    arch='arm64'
  fi

  os_arch="${os}-${arch}"

  download_uri="$(
    curl -fsSL https://api.github.com/repos/jdx/mise/releases/latest \
    | ${ggrep} -E '"browser_download_url"' \
    | ${ggrep} -E "${os_arch}\"$" \
    | ${ggrep} -E -o 'https://.*[^"]'
  )"

  mkdir -p "${HOME}/.local/bin"
  curl -fsSL -o "${HOME}/.local/bin/mise" "${download_uri}"
  chmod +x "${HOME}/.local/bin/mise"
fi

# mise also has a 'trust' concept for config files, so setting this should let it trust anything
# under the given director(ies)
export MISE_TRUSTED_CONFIG_PATHS="${HOME}"

### Overrides that may exist on the specific machine, these should obviously be run last
printf 'NOTE: any shell overrides should go into "~/.overridesrc"\n'
if [[ -f "${HOME}/.overridesrc" ]] ; then
  # shellcheck disable=SC1091
  source "${HOME}/.overridesrc"
fi
