#!/usr/bin/env zsh

# Shared shell rc file
source "${HOME}/.sharedrc"

### ZSH stuff
HISTFILE=~/.zsh_history
HISTSIZE=5000
SAVEHIST=5000
HISTDUP=erase
setopt appendhistory
setopt sharehistory
setopt incappendhistory
setopt hist_ignore_all_dups
setopt hist_save_no_dups
setopt hist_ignore_dups
setopt hist_find_no_dups
source /usr/share/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh || true

### mise-en-place
eval "$(mise activate zsh)"

# shellcheck disable=SC1091
source "${HOME}/.sharedrc-final"
