[settings]
idiomatic_version_file_enable_tools = []
experimental = true

[settings.pipx]
uvx = true

[env]
# Allows tools installed via the cargo backend to skip any Git auth configs that it tries to set on
# its own, and just what the host has configured
CARGO_NET_GIT_FETCH_WITH_CLI = true

[tools]
bats = "1.12.0"
btop = "1.4.5"
buf = "1.57.2"
go = "1.25.1"
jq = "1.8.1"
kubectl = "1.34.1"
packer = "1.14.2"
protobuf = "32.1"
python = "3.13.7"
ripgrep = "14.1.1"
shellcheck = "0.11.0"
terraform = "1.13.3"
uv = "0.8.18"
vault = "1.20.3"
