[settings]
idiomatic_version_file_enable_tools = []
experimental = true
yes = true

[settings.pipx]
uvx = true

[env]
# Allows tools installed via the cargo backend to skip any Git auth configs that it tries to set on
# its own, and just what the host has configured
CARGO_NET_GIT_FETCH_WITH_CLI = true

[tools]
"github:Wilfred/difftastic" = "0.65.0"
aws = "2.31.3"
bats = "1.12.0"
btop = { version = "1.4.5", os = ["linux"] }
buf = "1.57.2"
fd = "10.3.0"
github-cli = "2.79.0"
go = "1.25.2"
go-jsonnet = "0.21.0"
gcloud = "541.0.0"
helm = "3.19.0"
jq = "1.8.1"
k9s = "0.50.13"
kind = "0.30.0"
kubectl = "1.34.1"
kustomize = "5.7.1"
packer = "1.14.2"
protobuf = "32.1"
python = "3.13.7"
ripgrep = "14.1.1"
shellcheck = "0.11.0"
skaffold = "2.16.1"
terraform = "1.13.3"
uv = "0.8.18"
vault = "1.20.3"
yq = "4.48.1"
